// Add a tool = add one entry here (+ widget config in components/ToolWidget.tsx + optional content in lib/content.ts).
export type Category = "Creator" | "Finance" | "Everyday" | "Text & Productivity";
export type Tool = { slug: string; name: string; category: Category; short: string; title: string; description: string; faqs: { q: string; a: string }[] };
const f = (q: string, a: string) => ({ q, a });
export const tools: Tool[] = [
 { slug: "youtube-money-calculator", name: "YouTube Money Calculator", category: "Creator", short: "Estimate ad revenue from views.", title: "YouTube Money Calculator – Estimate Earnings per View (2026)", description: "Estimate monthly and yearly YouTube ad revenue from views and RPM. Free, instant, no sign-up.", faqs: [f("How accurate is it?", "It is an estimate. Real RPM varies by niche, audience location and season."), f("What is RPM?", "Revenue per 1,000 views after YouTube's share is taken out.")] },
 { slug: "tiktok-money-calculator", name: "TikTok Money Calculator", category: "Creator", short: "Estimate Creator Rewards income.", title: "TikTok Money Calculator – Estimate Creator Earnings", description: "Estimate TikTok earnings from views and a per-1,000-view rate. Free and instant.", faqs: [f("Does TikTok pay per view?", "Payouts depend on program eligibility, qualified views and region."), f("What rate should I use?", "Many creators see low rates; test a range of values.")] },
 { slug: "instagram-engagement-calculator", name: "Instagram Engagement Calculator", category: "Creator", short: "Work out your engagement rate.", title: "Instagram Engagement Calculator – Free Engagement Rate Tool", description: "Calculate Instagram engagement rate from likes, comments and followers.", faqs: [f("What is a good rate?", "Roughly 1–3% is common for mid-size accounts; it varies by niche."), f("Which formula is used?", "(Likes + comments) ÷ followers × 100.")] },
 { slug: "emi-calculator", name: "EMI Calculator", category: "Finance", short: "Monthly loan instalments.", title: "EMI Calculator – Monthly Loan Payment & Total Interest", description: "Calculate monthly loan instalments, total interest and total repayment.", faqs: [f("What does EMI stand for?", "Equated monthly instalment."), f("Does it include fees?", "No. Add lender fees separately.")] },
 { slug: "sip-calculator", name: "SIP Calculator", category: "Finance", short: "Project regular investing growth.", title: "SIP Calculator – Monthly Investment Return Estimator", description: "Estimate the future value of regular monthly investments at an assumed return.", faqs: [f("Are returns guaranteed?", "No. Markets fluctuate; this is an illustration."), f("Is it for UK users?", "Yes, it works for any monthly saving plan in any currency.")] },
 { slug: "compound-interest-calculator", name: "Compound Interest Calculator", category: "Finance", short: "See how savings compound.", title: "Compound Interest Calculator – Free Savings Growth Tool", description: "Calculate compound interest with a chosen compounding frequency.", faqs: [f("What is compounding?", "Earning interest on prior interest."), f("Monthly vs yearly?", "More frequent compounding gives slightly higher growth.")] },
 { slug: "gst-calculator", name: "GST Calculator", category: "Finance", short: "Add or remove GST/VAT.", title: "GST / VAT Calculator – Add or Remove Tax Instantly", description: "Add or remove GST or VAT from any amount. Works for any rate, including UK 20% VAT.", faqs: [f("Does it work for VAT?", "Yes, enter your VAT rate, e.g. 20 for UK standard rate."), f("How is tax removed?", "Gross ÷ (1 + rate).")] },
 { slug: "age-calculator", name: "Age Calculator", category: "Everyday", short: "Exact age in years, months, days.", title: "Age Calculator – Exact Age in Years, Months and Days", description: "Find your exact age and days lived from a date of birth.", faqs: [f("Is the date format important?", "Use the date picker to avoid confusion between US and UK formats."), f("Leap years?", "They are handled by the calendar.")] },
 { slug: "password-generator", name: "Password Generator", category: "Text & Productivity", short: "Strong random passwords.", title: "Password Generator – Create Strong Random Passwords", description: "Generate strong random passwords in your browser. Nothing is sent to a server.", faqs: [f("Is it stored?", "No. Generation runs locally in your browser."), f("How long?", "Use 16+ characters.")] },
 { slug: "qr-code-generator", name: "QR Code Generator", category: "Everyday", short: "Make QR codes for links or text.", title: "QR Code Generator – Free QR Codes for URLs and Text", description: "Create a QR code for any link or text and download it as a PNG.", faqs: [f("Do codes expire?", "Static codes made here do not expire."), f("Is it free?", "Yes.")] },
 { slug: "word-counter", name: "Word Counter", category: "Text & Productivity", short: "Count words and reading time.", title: "Word Counter – Words, Sentences & Reading Time", description: "Count words, characters, sentences and estimated reading time as you type.", faqs: [f("Are spaces counted?", "Both with and without spaces are shown."), f("Reading speed?", "About 238 words per minute.")] },
 { slug: "character-counter", name: "Character Counter", category: "Text & Productivity", short: "Count characters for limits.", title: "Character Counter – Check Limits for X, SEO and More", description: "Count characters with and without spaces for social posts and meta tags.", faqs: [f("Meta description length?", "Around 150–160 characters is typical."), f("Emoji?", "Some emoji count as more than one character.")] },
 { slug: "percentage-calculator", name: "Percentage Calculator", category: "Finance", short: "Quick percentage maths.", title: "Percentage Calculator – X% of Y and Percent Change", description: "Find a percentage of a number, or what percent one number is of another.", faqs: [f("How do I find X% of Y?", "Y × X ÷ 100."), f("Percent change?", "(New − old) ÷ old × 100.")] },
 { slug: "salary-calculator", name: "Salary Calculator", category: "Finance", short: "Gross to take-home estimate.", title: "Salary Calculator – Gross to Net Take-Home Estimate", description: "Estimate take-home pay from gross salary using a flat effective tax rate.", faqs: [f("Is it exact?", "No. It uses a single effective rate, not actual US/UK tax bands."), f("Which rate?", "Check your payslip or official tax tables.")] },
 { slug: "mortgage-calculator", name: "Mortgage Calculator", category: "Finance", short: "Monthly mortgage payments.", title: "Mortgage Calculator – Monthly Payment & Total Interest", description: "Estimate monthly mortgage payments from price, deposit, rate and term.", faqs: [f("Does it include taxes?", "No. Add property tax, insurance or fees separately."), f("Deposit vs down payment?", "Same thing; enter the amount you pay upfront.")] },
];
export const categories: Category[] = ["Creator", "Finance", "Everyday", "Text & Productivity"];
export const getTool = (s: string) => tools.find((t) => t.slug === s);
export function related(slug: string, n = 6) {
  const cur = getTool(slug); const others = tools.filter((t) => t.slug !== slug);
  return [...others.filter((t) => t.category === cur?.category), ...others.filter((t) => t.category !== cur?.category)].slice(0, n);
}
